# Q1: Import numpy library

In [21]:
# write your code here 
import numpy as np 

# Q2: Generate a sequence of 15 floats using linspace() function

In [22]:
# write your code here ^_^
seq = np.linspace(0,3,15)
seq

array([0.        , 0.21428571, 0.42857143, 0.64285714, 0.85714286,
       1.07142857, 1.28571429, 1.5       , 1.71428571, 1.92857143,
       2.14285714, 2.35714286, 2.57142857, 2.78571429, 3.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [23]:
array_1 = np.array([[[1.1, 2.1, 3.1],[4.1, 5.1, 6.1]],
                   [[7.1, 8.1, 9.1],[10.1, 11.1, 12.1]]])
array_1

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [24]:
# write your code here ^_^
# Q1 Array's type
array_1.dtype
# Q2 Array's elements datatype
type(array_1)
# Q3 Array's shape.
array_1.shape


(2, 2, 3)

In [25]:
# Q2 Array's elements datatype
type(array_1)

numpy.ndarray

In [26]:
# Q3 Array's shape.
array_1.shape

(2, 2, 3)

In [27]:
# Q4 Array's size.
array_1.size

12

In [28]:
#Q5 Array's dimention.
array_1.ndim

3

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [30]:
# write your code here ^_^
array_2 = array_1.reshape(2, 2, 3, 1)
array_2

array([[[[ 1.1],
         [ 2.1],
         [ 3.1]],

        [[ 4.1],
         [ 5.1],
         [ 6.1]]],


       [[[ 7.1],
         [ 8.1],
         [ 9.1]],

        [[10.1],
         [11.1],
         [12.1]]]])

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [31]:
# write your code here ^_^
array_2.shape

(2, 2, 3, 1)

In [32]:
array_2.ndim

4

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [33]:
# write your code here ^_^

array_3 = array_2.astype(int)
array_3

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 8],
         [ 9]],

        [[10],
         [11],
         [12]]]])

In [34]:
for i in np.nditer(array_3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [36]:
# write your code here ^_^
array_3[1, 0, 1, 0]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [9]:
# write your code here ^_^
array_3[0, 1, 1:3, 0]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [38]:
# write your code here ^_^
np.where(array_3==8)

(array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [39]:
# write your code here ^_^
array_4 = array_3.reshape(2, 3, 2)
array_4

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [12]:
# write your code here ^_^

# Q12.2: Join the arrays along rows with axis = 1 

In [42]:
# write your code here ^_^
array_1 = np.array([['1', '2'], ['3', '4']])
array_2= np.array([['5', '6'], ['7', '8']])
arr5 = np.concatenate((array_1, array_2))
np.concatenate((array_1, array_2), axis=1)

array([['1', '2', '5', '6'],
       ['3', '4', '7', '8']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [43]:
# write your code here ^_^
np.split(array_1, [1], axis=1)

[array([['1'],
        ['3']], dtype='<U1'),
 array([['2'],
        ['4']], dtype='<U1')]